sudo:
  false

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

before_install:
  - openssl aes-256-cbc -K $encrypted_fb7962ff6e71_key -iv $encrypted_fb7962ff6e71_iv -in .credentials.json.enc -out .credentials.json -d

install:
  - pip install -Urrequirements.dev.txt

script:
  - python run.py test

after_success:
  - python run.py report
